Pizza_Portal/Models/ErrorViewModel.cs
using System;

namespace Pizza_Portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pizza_Portal/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Portal.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string Email { get; set; }

        public string  UserId { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }
}

Pizza_Portal/Models/OrderItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Portal.Models
{
    public class OrderItem
    {
        [Key]
        public int Id { get; set; }

        public int Amount { get; set; }

        public double Price { get; set; }

        public int PizzaId { get; set; }
        [ForeignKey("PizzaId")]
        public Pizza Pizza { get; set; }

        public int OrderId { get; set; }
        [ForeignKey("OrderId")]
        public Order Order { get; set; }
    }
}

Pizza_Portal/Models/Pizza.cs
using Pizza_Portal.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Portal.Models
{
    public class Pizza : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Category { get; set; }

        public double Price { get; set; }

        public string ImageURL { get; set; }
    }
}

Pizza_Portal/Models/ShoppingCartItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Portal.Models
{
    public class ShoppingCartItem
    {
        [Key]
        public int Id { get; set; }

        public Pizza Pizza { get; set; }

        public int Amount { get; set; }

        public string ShoppingCartId { get; set; }
    }
}

Pizza_Portal/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Pizza_Portal.Data.Cart;
using Pizza_Portal.Data.Services;
using Pizza_Portal.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Pizza_Portal.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IPizzaService _pizzaService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IPizzaService pizzaService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _pizzaService = pizzaService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

/*        public async Task<IActionResult> Index()
        {
            string userId = "";
            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }*/

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _pizzaService.GetPizzaByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);

            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _pizzaService.GetPizzaByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = "";
            string userEmailAddress = "";

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View("OrderCompleted", orders);
        }


    }
}

Pizza_Portal/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pizza_Portal.Data;
using Pizza_Portal.Data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_Portal.Controllers
{
    public class PizzaController : Controller
    {
        private readonly IPizzaService _service;
        private readonly IOrdersService _ordersService;

        public PizzaController(IPizzaService service, IOrdersService ordersService)
        {
            _service = service;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            await _ordersService.DeleteAllOrderAsync();
            var allPizzas = await _service.GetAllAsync();
            return View(allPizzas);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allPizzas = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allPizzas.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString) || n.Category.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allPizzas);
        }
    }
}

Pizza_Portal/Views/Orders/Index.cshtml
@model List<Order>

@{
    ViewData["Title"] = "All Orders";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>List of all your orders</h4>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Items</th>
                    <th>Total</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td class="align-middle">@order.Id</td>
                        <td class="align-middle">
                            <ul style="list-style-type:none">

                                @foreach (var item in order.OrderItems)
                                {
                                    <li>
                                        <div class="alert alert-info" role="alert">
                                            <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString("c")] - @item.Pizza.Name
                                        </div>
                                    </li>
                                }

                            </ul>
                        </td>
                        <td class="align-middle">
                            @order.OrderItems.Select(m => m.Pizza.Price * m.Amount).Sum().ToString("c")
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Pizza_Portal/Views/Orders/OrderCompleted.cshtml
@model List<Order>

@{
    ViewData["Title"] = "All Orders";
}

<div class="row">
    <div class="col-md-6 offset-3 alert alert-success text-center">
        <h2>Order Completed Successfully!</h2>
        <hr />
        <p>Thank You!</p>
    </div>
</div>

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Order Summary</h4>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Items</th>
                    <th>Total</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td class="align-middle">@order.Id</td>
                        <td class="align-middle">
                            <ul style="list-style-type:none">

                                @foreach (var item in order.OrderItems)
                                {
                                    <li>
                                        <div class="alert alert-info" role="alert">
                                            <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString("c")] - @item.Pizza.Name
                                        </div>
                                    </li>
                                }

                            </ul>
                        </td>
                        <td class="align-middle">
                            @order.OrderItems.Select(m => m.Pizza.Price * m.Amount).Sum().ToString("c")
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Pizza_Portal/Views/Orders/ShoppingCart.cshtml
@using Pizza_Portal.Data.ViewModels;
@model ShoppingCartVM

@{ 
    ViewData["Title"] = "Shopping Cart Summary";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h2>Your Shopping Cart Summary</h2>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Selected Amount</th>
                    <th>Pizza</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                {

                    <tr>
                        <td class="align-middle">@item.Amount</td>
                        <td class="align-middle">@item.Pizza.Name</td>
                        <td class="align-middle">@item.Pizza.Price.ToString("c")</td>
                        <td class="align-middle">@((item.Amount*item.Pizza.Price).ToString("c"))</td>
                        <td class="align-middle">
                            <a class="text-danger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart" asp-route-id="@item.Pizza.Id">
                                <i class="bi bi-cart-dash"></i>
                            </a>

                            <a class="text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Pizza.Id">
                                <i class="bi bi-cart-plus"></i>
                            </a>
                        </td>
                    </tr>

                }

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total:</b></td>
                    <td>
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div class="text-center">
            <div class="btn-group">
                <a class="btn btn-outline-primary" asp-action="CompleteOrder">
                    Complete Order
                </a>
                <a class="btn btn-outline-success" asp-controller="Pizza" asp-action="Index">
                    Add more items
                </a>
            </div>
        </div>

    </div>
</div>

Pizza_Portal/Views/Pizza/Index.cshtml
@model IEnumerable<Pizza>

@{
    ViewData["Title"] = "List of Pizzas";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0" style="height: 680px;">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                </h5>
                            </p>
                        </div>
                    </div>    
                    <div class="col-md-12">
                        <center>
                            <img src="@item.ImageURL" height="300px" width="70%" alt="@item.Name" style="top:0;" />
                        </center>
                        <div class="card-body">
                            <p class="card-text"><b>Description: </b>@item.Description</p>
                            <p class="card-text"><b>Price: </b>@item.Price.ToString("c")</p>
                            <p class="card-text"><b>Category: </b>@item.Category</p>
                        </div>
                    </div>
                    <div class="col-md-12" style="bottom: 0; left:0; position: absolute">
                        
                            <p class="card-text">
                                <center>
                                    <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                                </center>
                            </p>
                        
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Pizza_Portal/Views/Shared/Components/ShoppingCartSummary/Default.cshtml
@model int;

@if (Model > 0)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Orders" asp-action="ShoppingCart">
            <i class="bi bi-cart4"></i> @Model
        </a>
    </li>
}

Pizza_Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza_Portal</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pizza" asp-action="Index">Pizza_Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="Pizza" asp-action="Index"><i class="fas fa-pizza-slice"></i> Pizza</a>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Pizza" asp-action="Filter">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a Pizza..." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Pizza_Portal
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>